/*
 * Fases da campanha do Hora do Rush.
 *
 * GERADO por tools/build-levels.js — nao edite a mao.
 * Cada fase foi resolvida por busca em largura: "m" e o numero MINIMO de
 * movimentos comprovado, nao uma estimativa.
 *
 * b = tabuleiro 6x6 em 36 caracteres (o = vazio, A = carro vermelho)
 * m = movimentos minimos   t = faixa de dificuldade
 */
window.RUSH_TIERS = [{"id":"aprendiz","nome":"Aprendiz","levels":12},{"id":"motorista","nome":"Motorista","levels":12},{"id":"taxista","nome":"Taxista","levels":12},{"id":"caminhoneiro","nome":"Caminhoneiro","levels":12},{"id":"piloto","nome":"Piloto","levels":12},{"id":"lenda","nome":"Lenda","levels":12}];
window.RUSH_LEVELS = [
  {"b":"ooooCCEEooooooAAoBoooooBooooooooooDD","m":2,"t":"aprendiz"},
  {"b":"ooDDoooooooooAABCoEooBCoEooBCooooooo","m":3,"t":"aprendiz"},
  {"b":"oooooooooBBDAAoEoDoooEoDoooCCCoooooo","m":4,"t":"aprendiz"},
  {"b":"oDDooEoooooEAABCoEooBCoooooCoooooooo","m":4,"t":"aprendiz"},
  {"b":"oooBoEoooBCEoAABCEooooooDoooooDooooo","m":4,"t":"aprendiz"},
  {"b":"ooEBooooEBoCAAoBoCFooooCFoooDDoooooo","m":4,"t":"aprendiz"},
  {"b":"EEooCoooBDCoAABDCooFFDoooooooooooooo","m":4,"t":"aprendiz"},
  {"b":"oooFFEooCooEAACoDEooCoDooBBooooooooo","m":5,"t":"aprendiz"},
  {"b":"DooBooDooBCooAABCoooFoCoooFoEEoooooo","m":6,"t":"aprendiz"},
  {"b":"oooooCooDooCAADooCEoDBBoEooooooFFFoo","m":7,"t":"aprendiz"},
  {"b":"CooooBCooooBAAFooBooFoooDDFoooEEEooo","m":7,"t":"aprendiz"},
  {"b":"oooooooooBEEoAABooCCCBooFoooooFooDDD","m":7,"t":"aprendiz"},
  {"b":"ooooooooEoooAAEoooDoEFFFDoCCBoooooBo","m":7,"t":"motorista"},
  {"b":"oGooCooGEECDoGAACDoooBoDoooBFFoooooo","m":8,"t":"motorista"},
  {"b":"oooooooDDoCBooAACBooFoCoooFGGoooFEEo","m":9,"t":"motorista"},
  {"b":"DDooHHooBoGGAABooFooBooFCEEEoFCooooo","m":9,"t":"motorista"},
  {"b":"ooDBooEEDBooAAoBooFCGGGoFCooooFooooo","m":9,"t":"motorista"},
  {"b":"ooooooooBGoCAABGoCDoBEEoDoooHoFFFoHo","m":9,"t":"motorista"},
  {"b":"ooCoooooCoFFAACoooGGGooEBooooEBoDDoE","m":10,"t":"motorista"},
  {"b":"oooooooooooDoAAoCDEEEoCooBFoCooBFGGG","m":11,"t":"motorista"},
  {"b":"oooDooFFFDooAAHDCoooHoCoGoEEBBGooooo","m":12,"t":"motorista"},
  {"b":"oooEoooooEoGAAoFoGBHIFooBHICCDBooooD","m":13,"t":"motorista"},
  {"b":"ooooooBooEooBAAEGooIoEGDFICCoDFoHHoD","m":13,"t":"motorista"},
  {"b":"IEEoooIoBoooAABoFooooHFoGGGHDDoCCCoo","m":13,"t":"motorista"},
  {"b":"ooHHBBoGGoDoooAADoECCCDoEoIFFoooIooo","m":13,"t":"taxista"},
  {"b":"ooEDDoooEooooAAoFoHHBBFooGooFooGCCCo","m":14,"t":"taxista"},
  {"b":"ooDoooooDoooAAGoBoHHGoBooECCBooEFFoo","m":15,"t":"taxista"},
  {"b":"IEEHFoIooHFoAABoooooBoooGGGDDoCCCooo","m":15,"t":"taxista"},
  {"b":"oIIFoooBoFGooBAAGoHHEoGoooECCCDDDooo","m":15,"t":"taxista"},
  {"b":"EoCCIIEooBJJAAFBooooFGGDHHHooDoooooD","m":15,"t":"taxista"},
  {"b":"EHHBBoEGGoDoAAooDoCCCoDoooIFFoooIooo","m":16,"t":"taxista"},
  {"b":"CoooooCooEoooAAEoooIIEoHoFGGDHoFBBDH","m":17,"t":"taxista"},
  {"b":"oGoBBKoGooFKoAAIFEoJJIFECooHoECooHDD","m":18,"t":"taxista"},
  {"b":"IGGBFFIooBooAADBoJooDoEJoHHHECoooooC","m":19,"t":"taxista"},
  {"b":"oCoBBoKCooDoKCAADGIIEoDGooEJJFHHHooF","m":19,"t":"taxista"},
  {"b":"FJJoBoFoEoBIAAEooICCCHHIooooGGooooDD","m":19,"t":"taxista"},
  {"b":"HLooBBHLooFFoAAGDoCCCGDKooIEEKooIJJK","m":19,"t":"caminhoneiro"},
  {"b":"CCEooGKDEooGKDAABGFFFIBooooIJJooHHHo","m":20,"t":"caminhoneiro"},
  {"b":"IBBCCCIooGGLAAooELDDDHELooJHFFooJKKo","m":21,"t":"caminhoneiro"},
  {"b":"oBBBoFoCCooFAAJEHFIIJEHoGKKMHoGLLMDD","m":21,"t":"caminhoneiro"},
  {"b":"FFGJDIooGJDIoooAAIoCCBooEKoBLLEKooHH","m":21,"t":"caminhoneiro"},
  {"b":"DDFFFEooCCoEAAKoIGJoKoIGJoKoBBLLHHoo","m":21,"t":"caminhoneiro"},
  {"b":"DoEJFFDoEJBoDAACBooooCLLooIGGHKKIooH","m":22,"t":"caminhoneiro"},
  {"b":"oEIIFooEBBFoJAAGFoJooGHHJoKCCDooKooD","m":23,"t":"caminhoneiro"},
  {"b":"GGHJoILoHJEILAABEIoCCBooFKoDDoFKoooo","m":24,"t":"caminhoneiro"},
  {"b":"oDooMMoDJJKoHAACKBHIICKBHoLEEBFFLoGG","m":25,"t":"caminhoneiro"},
  {"b":"EBooCCEBooGFoBAAGFDDHJGoooHJIIoLLKKo","m":25,"t":"caminhoneiro"},
  {"b":"ooCCCoIIBEDHAABEDHooKFFoGoKMMJGoLLLJ","m":25,"t":"caminhoneiro"},
  {"b":"oBBBGoMMoEGoAAoEGHJoIKKHJFIDDHoFLLCC","m":25,"t":"piloto"},
  {"b":"oBBBKoHCCEKLHAAEKLoIGFFMoIGDDMoJJooo","m":26,"t":"piloto"},
  {"b":"IoGGEEIoJoooAAJooooKKFDDBBBFHooCCFHo","m":27,"t":"piloto"},
  {"b":"JLLoEEJMMCDBJAACDBKKFoDBooFoGGoHHoII","m":27,"t":"piloto"},
  {"b":"GoLLCCGoIIJBGAAMJBHHDMJBooDEEoFFooKK","m":27,"t":"piloto"},
  {"b":"EoBBBoEoJKCCAAJKGooFHHGDMFIIGDMoLLoD","m":27,"t":"piloto"},
  {"b":"ooIIIMLLooKMAABCKoHGBCJJHGEoFFDDEooo","m":28,"t":"piloto"},
  {"b":"ooJJJooEEDCoAABDCILMBFFILMHKKoGGHooo","m":29,"t":"piloto"},
  {"b":"oKLLEEIKoCDBIAACDBIJJoDBooFoGGMMFHHo","m":30,"t":"piloto"},
  {"b":"ooBLLLDDBoJIooAAJIoHFKKIoHFCGGoEECoo","m":31,"t":"piloto"},
  {"b":"oCCCoGHHBoDGAABoDMFJJEoMFoKEIILLKooo","m":31,"t":"piloto"},
  {"b":"KBBBIHKooJIHAAEJIFLLEooFoooCGGDDoCMM","m":31,"t":"piloto"},
  {"b":"oEEEoFooIIHFAABoHFKoBGGoKDDCMMLLLCJJ","m":31,"t":"lenda"},
  {"b":"MMMooooKKoCIAABoCIGFBHHIGFEDLLJJEDoo","m":33,"t":"lenda"},
  {"b":"oMMMoIFBBKJIFAAKJEDDCoJEooCLGGHHoLoo","m":34,"t":"lenda"},
  {"b":"ooCCCHoJJoMHAABoMKGoBEEKGoFDIILLFDoo","m":34,"t":"lenda"},
  {"b":"FoBBBIFCCKJIAADKJEMMDoJEoooLGGoooLHH","m":34,"t":"lenda"},
  {"b":"ooLJJJIILoHMooAAHMFEGGoMFECKDDBBCKoo","m":34,"t":"lenda"},
  {"b":"KoLLLHKooJIHAAoJIFEEDBIFooDBMMCCGGoo","m":35,"t":"lenda"},
  {"b":"oBBBoJGCCLKJGAALKFoEEMKFooDMHHIIDooo","m":36,"t":"lenda"},
  {"b":"JBBBoGJDDFNGoAAFNIMMHCoIooHCKKooEELL","m":38,"t":"lenda"},
  {"b":"oHHHJoGBBDJEGAADJEIIFMoEooFMKKLLooCC","m":39,"t":"lenda"},
  {"b":"FooBBBFCCDGoAAoDGMEEKoGMooKLIIHHoLJJ","m":40,"t":"lenda"},
  {"b":"DBBBooDLLoECAAoJECGGoJECooIMHHFFIMKK","m":40,"t":"lenda"}
];
